version: '3.9'

services:
  web:
    build: ./web/
    image: moe_web
    volumes:
      - ./web/:/app/
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: moe_api
    volumes:
      - ./moe/:/moe/moe
      - ./web/dist/:/app/dist/
      # - ./web/static/:/app/static/
    environment:
      - WEB_DIST=/app/dist/
    ports:
      - 5000:80
